version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: procurement-granite:latest
    container_name: procurement-granite-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  # Uncomment to add a simple UI (requires separate implementation)
  # ui:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   image: procurement-granite-ui:latest
  #   container_name: procurement-granite-ui
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - API_URL=http://api:8000
  #   depends_on:
  #     - api
  #   restart: unless-stopped 